version: "3.2"

services:
  mapdb:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simpsons-api
      MYSQL_USER: homer
      MYSQL_PASSWORD: simpson
    command: >
      mysqld --sql_mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --log-error-verbosity=2
    volumes:
      - simpsons-api-data:/var/lib/mysql

volumes:
  simpsons-api-data:
